---
title: "First post"
date: 2018-07-26
---
author: Quickstunt
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Now still under constraction, but will be ready soon.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
